language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --default-timeout 60 -r requirements.txt
    - pip install .
script:
    - flake8 rdftools test setup.py
    - pytest --cov=rdftools test/*.py
after_success:
    - coveralls
branches:
  only:
    - master
