language: python
python:
    - "3.6"
    - "3.7"
    - "pypy3"
install:
    - pip install --default-timeout 60 -r requirements.txt
    - pip install .
script:
    - flake8 rdftools test setup.py
    - pytest --cov=rdftools test/*.py
after_success:
    - coveralls
branches:
  only:
    - master
