language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --default-timeout 60 -r requirements.txt
    - pip install --default-timeout 60 coverage coveralls nose-timer && export HAS_COVERALLS=1
    - python setup.py install
    - pip install 
script:
    - flake8 rdftools
    - pytest --cov=divelog test/
after_success:
    - coveralls
branches:
  only:
    - master